apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - secret.yaml
  - postgres.yaml
  - redis.yaml
  - auth.yaml
  - catalog.yaml
  - order.yaml
  - cart.yaml
  - gateway.yaml
  - ingress.yaml

